---
- hosts: server-ubuntu 
  become: True
  tasks:
    - name: Install packages
      apt:
        name: "apache"
        state: "present"
    - name: Start Apache server
      service:
        name: apache
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
